version: 0.2

env:
  # Secrets ManagerからDocker Hubの認証情報を取得するための設定
  secrets-manager:
    DOCKERHUB_USERNAME: "docker-hub-credentials:username"
    DOCKERHUB_PASSWORD: "docker-hub-credentials:password"

phases:
  pre_build:
    commands:
      # AWS ECRへのログイン
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com
      # Docker Hubへのログイン
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      # Dockerイメージのビルド
      - docker build -t $ImageName -f ./Dockerfile .

  post_build:
    commands:
      # Dockerイメージにタグを付ける
      - docker tag $ImageName:latest 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest
      # イメージをECRにプッシュする
      - docker push 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest

artifacts:
  files:
    - '**/*'