version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "docker-hub-credentials:username"
    DOCKERHUB_PASSWORD: "docker-hub-credentials:password"

phases:
  pre_build:
    commands:
      # AWS ECRへのログイン
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com
      # Docker Hubへのログイン
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building the Docker image using multi-stage build..."
      - docker build -t my-app -f ./Dockerfile .

  post_build:
    commands:
      # ECRにタグ付けしてプッシュ
      - docker tag my-app:latest 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/springboot-app:latest
      - docker push 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/springboot-app:latest

      # --- ここから追加 ---
      # imagedefinitions.json ファイルを作成
      # ECRのリポジトリURIを構築
      - IMAGE_URI=$(printf '%s.dkr.ecr.%s.amazonaws.com/%s:latest' 513594376299 ap-northeast-1 springboot-app)
      - echo "[{\"name\":\"springboot-app\",\"imageUri\":\"$IMAGE_URI\"}]" > imagedefinitions.json
      # --- ここまで追加 ---

artifacts:
  files:
    - '**/*'
    # --- ここにimagedefinitions.jsonを追加 ---
    - imagedefinitions.json