version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "docker-hub-credentials:username"
    DOCKERHUB_PASSWORD: "docker-hub-credentials:password"

phases:
  pre_build:
    commands:
      # AWS ECRへのログイン
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com
      # Docker Hubへのログイン
      # Secrets Managerから取得したDOCKERHUB_PASSWORDとDOCKERHUB_USERNAMEを使用
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      # アプリケーションのビルドとDockerイメージのビルドを同時に行う
      - echo "Building the Docker image using multi-stage build..."
      - docker build -t $ImageName -f ./Dockerfile .

  post_build:
    commands:
      # ECRにタグ付けしてプッシュa
      - docker tag $ImageName:latest 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest
      - docker push 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest

artifacts:
  files:
    - '**/*'