version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "docker-hub-credentials:username"
    DOCKERHUB_PASSWORD: "docker-hub-credentials:password"

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building the application with Maven..."
      - mvn package
      - echo "Building the Docker image..."
      - docker build -t $ImageName -f ./Dockerfile .

  post_build:
    commands:
      - docker tag $ImageName:latest 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest
      - docker push 513594376299.dkr.ecr.ap-northeast-1.amazonaws.com/$ImageName:latest

artifacts:
  files:
    - '**/*'